# Generated by Django 4.1.3 on 2022-12-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Popular'), (3, 'Promo')], default=1),
        ),
    ]
